### ISSUE TITLE
changed layers config breaks bzar

### ISSUE THREAD

**Issue by ghost** [noi-techpark/it.bz.opendatahub.analytics.libs#4]
Hi @Piiit 

In 
https://analytics.opendatahub.bz.it/layers-config.json

there appeared a layer that has *two* elements in "stationType":

"stationType": [ "BikesharingStation", "Bicycle"]

versus every other integreen layer that has just one.

This breaks bzar right now.

Is this a mistake?

If not, what is the purpose of this? How should I handle this?

-- Chris

**Comment by Piiit** [comment]
Hi @chris-mair 

Yes this is a merged layer to show both stationtypes inside analytics.opendatahub.bz.it. That was afaik always like this, it is at the moment maybe only this type, but in the future it is possible that we have layers that merge more than 2 stationtypes into one representation.

I would just add those stationtypes as a CSV to the API call inside bzar... 

Example:
https://mobility.api.opendatahub.bz.it/v2/flat,node/Bicycle,BikesharingStation

This should be possible to be integrated into bzar. Let me know, if you see any problems with that?

**Comment by ghost** [comment]
Hi @Piiit 

I agree. Here is the pull request:

https://github.com/noi-techpark/it.bz.opendatahub.analytics.libs/pull/5

-- Chris
